Notifications and swipe pages
petarLits/book pull request #17
Opened 2024-09-19 11:53 UTC by petarLits

2024-09-19 12:20 UTC, UrosLITS requested changes

2024-09-19 12:20 UTC, UrosLITS commented on lib/data/firebase_message_manager.dart
> +  }
you can divide LocalFlutter notifications from FirebaseMessaging that's 2 different packages.

2024-09-19 12:20 UTC, UrosLITS commented on lib/home/view/home_page.dart
> +      if (data['action'] == 'bookChanged') {
can put constant here

2024-09-19 23:47 UTC, milicaLits requested changes

2024-09-19 23:47 UTC, milicaLits commented on lib/book/book_page/book_page_view.dart
> +            isMessageReceived = false;
Instead of using flag use getter for isMessageReceived

2024-09-25 11:23 UTC, milicaLits approved these changes

2024-09-25 11:34 UTC, UrosLITS approved these changes

2024-09-25 11:34 UTC, UrosLITS commented on lib/home/bloc/home_event.dart
> +  List<Object?> get props => [book, messageTitle, messageBody];
add comma here

2024-09-25 11:40 UTC, petarLits commented on lib/home/bloc/home_event.dart
> +  List<Object?> get props => [book, messageTitle, messageBody];
it will be fixed in next pull request

2024-09-25 11:40 UTC, merged