Home page view with hardcoded books
petarLits/book pull request #7
Opened 2024-08-27 12:46 UTC by petarLits

Finished for today. There is still work to do.

2024-08-28 12:58 UTC, lecicdjuro requested changes

2024-08-28 12:58 UTC, lecicdjuro commented on lib/app_routes.dart
> +        return _materialRoute(AddNewBook());
this is not the right place to make instance of new book. You should forward it using params

2024-08-28 12:58 UTC, lecicdjuro commented on lib/book.dart
> +    required this.docId,
required before optional

2024-08-28 12:58 UTC, lecicdjuro commented on lib/data/firebase_db_manager.dart
> +import '../book/book.dart';
we should not use relative path for imports. Try to use absolute path

2024-08-28 12:58 UTC, lecicdjuro commented on lib/home/bloc/home_event.dart
> +import '../../book/book.dart';
ditto

2024-08-28 12:58 UTC, lecicdjuro commented on lib/home/bloc/home_state.dart
> +import '../../book/book.dart';
ditto

2024-08-28 12:58 UTC, lecicdjuro commented on lib/home/bloc/home_bloc.dart
>      emit(AddingNewBook());
AddNewBookState

2024-08-28 12:58 UTC, lecicdjuro commented on lib/home/bloc/home_bloc.dart
> +    emit(SavedBook(book: event.book));
SaveBookState

2024-08-28 12:58 UTC, lecicdjuro commented on lib/home/view/add_new_book.dart
> +                        if (pickedImage != null) {
AddBookImageEvent

2024-08-28 12:58 UTC, lecicdjuro commented on lib/home/view/add_new_book.dart
> +                        if (pickedImage != null) {
and forward file

2024-08-30 10:12 UTC, lecicdjuro requested changes

2024-08-30 10:12 UTC, lecicdjuro commented on lib/data/firebase_db_manager.dart
> +    final folderRef= storageRef.child(book.title);
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/data/firebase_db_manager.dart
> +  Future<void> uploadBook(Book book) async{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/data/firebase_db_manager.dart
> +
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/data/firebase_db_manager.dart
> +  Future<void> uploadBookImageAndGetUrl(Book book) async{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_bloc.dart
> +    try{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_bloc.dart
> +    }on Exception catch (e){
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_bloc.dart
> +    try{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_bloc.dart
> +    }on Exception catch(e){
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_bloc.dart
> +  Future<void> _onAddBookImage(AddBookImage event, Emitter<HomeState> emit) async{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_bloc.dart
> +  Future<void> _onSaveNewBook(SaveNewBook event, Emitter<HomeState> emit)async {
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_event.dart
> +class SaveNewBook extends HomeEvent{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_event.dart
> +class AddBookImage extends HomeEvent{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_event.dart
> +class UploadBookImageAndGetUrl extends HomeEvent{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_event.dart
> +class DeleteBookImage extends HomeEvent{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_state.dart
> +class AddBookImageState extends HomeState{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_state.dart
> +class UploadedBookImageAndUrlGotState extends HomeState{
ditto

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_state.dart
> +class DeletedBookImage extends HomeState{
ditto

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/bloc/home_state.dart
> +class LoadingState extends HomeState{
ditto

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/view/add_new_book.dart
> +      if (state is SaveBookState) {
SavedBookState

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/view/add_new_book.dart
> +      }else if(state is DeletedBookImage){
fkr at

2024-08-30 10:12 UTC, lecicdjuro commented on lib/home/view/home_page.dart
> +                          '${AppLocalizations.of(context)!.author} ${book.author}',
use localization with params

2024-08-30 10:12 UTC, lecicdjuro commented on lib/login/bloc/login_bloc.dart
> +    finally{
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/login/view/login_page.dart
> +      }else if(state is LoadingState){
format

2024-08-30 10:12 UTC, lecicdjuro commented on lib/login/view/login_page.dart
> +      }else if(state is LoadedState){
ditto

2024-08-30 11:32 UTC, milicaLits commented on lib/app_user.dart
> +  List<Object?> get props => [firstName, lastName, email, password, isAdmin];
Add comma after last parameter and format

2024-08-30 11:32 UTC, milicaLits commented on lib/home/bloc/home_bloc.dart
>        await FirebaseAuthManager.instance.signOut();
No comma when only one parameter. Format.

2024-08-30 11:32 UTC, milicaLits commented on lib/home/bloc/home_state.dart
> +
Format

2024-08-30 12:30 UTC, milicaLits approved these changes

2024-09-02 08:18 UTC, lecicdjuro approved these changes

2024-09-02 08:20 UTC, merged