Adding new book page to list and book page view started
petarLits/book pull request #8
Opened 2024-09-04 13:03 UTC by petarLits

2024-09-04 13:04 UTC, lecicdjuro commented
Bad title

2024-09-04 13:11 UTC, UrosLITS approved these changes

2024-09-09 13:25 UTC, milicaLits commented on lib/book/book_page/new_book_page.dart
>            decodedImage = await decodeImageFromList(image!.readAsBytesSync());
Maybe put this function in event handler.

2024-09-09 13:25 UTC, milicaLits commented on lib/book/book_page/book_page_view.dart
> +            child: CircularProgressIndicator(),
I don't think you need Loading and Loaded State if you you build ProgressIndicator when the state is other than DisplayBookPage State.

2024-09-10 08:48 UTC, milicaLits commented on lib/book/bloc/book_page_state.dart
> +  AddBookPageImageState({required this.image, required this.decodedImage});
format?

2024-09-10 08:48 UTC, milicaLits approved these changes

2024-09-10 08:58 UTC, UrosLITS requested changes

2024-09-10 08:58 UTC, UrosLITS commented on lib/book/bloc/book_page_bloc.dart
>    }
what if this call fails?

2024-09-10 10:24 UTC, UrosLITS approved these changes

2024-09-10 10:37 UTC, merged